version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-01

    steps:
      - checkout

      # Installer curl
      - run:
          name: Install Curl
          command: sudo apt-get update && sudo apt-get install -y curl

      # Construction de l'image Docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t nodeapp .

      # Démarrer le serveur dans un conteneur Docker
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name nodeapp_container nodeapp

      # Attendre que le serveur démarre
      - run:
          name: Wait for Server Startup
          command: sleep 10

      # Vérifier la réponse du serveur
      - run:
          name: Check Page Response
          command: |
            curl -I http://localhost:8080

workflows:
  version: 2
  build:
    jobs:
      - build
