version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Installer Yarn
      - run:
          name: Install Yarn
          command: |
            sudo apt-get update && sudo apt-get install -y curl
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install -y yarn

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t nodeapp .
      # Démarrer le serveur dans un conteneur Docker
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name nodeapp_container nodeapp

      # Attendre que le serveur démarre
      - run:
          name: Wait for Server Startup
          command: sleep 10
      - run:
          name: Check Page Response
          command: |
            curl -I http://localhost:8080
      # Tester l'image Docker (facultatif)
      # Ajoutez ici vos étapes de test si nécessaire

      # Publication de l'image Docker sur Docker Hub (facultatif)
      # Remplacez 'nom_de_votre_image' par le nom de votre image sur Docker Hub
      # - run:
      #     name: Publish Docker Image
      #     command: |
      #       docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      #       docker tag nom_de_votre_image $DOCKERHUB_USERNAME/nom_de_votre_image
      #       docker push $DOCKERHUB_USERNAME/nom_de_votre_image

workflows:
  version: 2
  build:
    jobs:
      - build
