version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-01

    steps:
      - checkout

      - run:
          name: Install Curl
          command: sudo apt-get update && sudo apt-get install -y curl

      - run:
          name: Build Docker Image
          command: |
            docker build -t nodeapp .

      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name nodeapp_container nodeapp

      - run:
          name: Wait for Server Startup
          command: sleep 10

      - run:
          name: Check Page Response
          command: |
            curl -I http://localhost:8080

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUBPASSWORD" | docker login -u "$DOCKERHUBUSER" --password-stdin

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker tag nodeapp "d0coeur/nodeapp"
            docker push "d0coeur/nodeapp"

workflows:
  version: 2
  build:
    jobs:
      - build
